### ISSUE TITLE
add `title` in catalog.json

### ISSUE THREAD

**Issue by JinIgarashi** [UNDP-Data/geo-undpstac-pipeline#8]
https://undpgeohub.blob.core.windows.net/stacdata/nighttime-lights/2023/catalog.json
https://undpgeohub.blob.core.windows.net/stacdata/nighttime-lights/2023/09/catalog.json

There is no title in catalog.json

<img width="589" alt="image" src="https://github.com/UNDP-Data/geo-undpstac-pipeline/assets/2639701/ca0e96a2-754c-42fa-b5b1-a3ad6b8fb403">

However, there can be both title and description at catalog.json according to the STAC doc.

https://github.com/radiantearth/stac-spec/blob/master/catalog-spec/catalog-spec.md

You can add a short title in catalog.json, this can help users to understand it

**Comment by iferencik** [comment]
theer is a title in every catalog
yearly
![image](https://github.com/UNDP-Data/geo-undpstac-pipeline/assets/92793531/d53195c0-6742-41ca-b0dc-14ea28b0af5b)
monthly
![image](https://github.com/UNDP-Data/geo-undpstac-pipeline/assets/92793531/77b596fa-db48-4d83-a9b0-0845fc37017f)
